# Generated by Django 6.0.6 on 2026-06-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
